export { default as Home } from "./home/home";
export { default as Login } from "./login/login";
export { default as Root } from "./root/root";
export { default as RegForm } from "./regform/regform";
export { default as NotFound } from "./notfound/notfound";
export { default as Personas } from "./personas/personas";
export { default as Torneos } from "./torneos/torneos";
export { default as Entrenamiento } from "./entrenamiento/entrenamiento";
export { default as Pagos } from "./pagos/pagos";
